### ISSUE TITLE
Debian upload?

### ISSUE THREAD

**Issue by dzatoah** [vfreex/mdns-reflector#3]
Hey is something planned regarding a Debian Upload?

Maybe we want to use this program in our own project (Debian Edu Router).
A quick response would be appreciated since there is hope that we can make it into Debian 12 before its freeze.

I've tested this software on Debian Bookworm and it works.

**Comment by sunweaver** [comment]
@dzatoah We won't make it for Debian 12 anymore. The deadline for NEW uploads ended today. But we can provide mdns-reflector in Debian long term, starting with Debian 13.

**Comment by sunweaver** [comment]
Packaging repo: https://salsa.debian.org/debian-edu-pkg-team/mdns-reflector
Debian ITP: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1030803 (intent to package declaration)

I couldn't wait because this project sounds awesome and simple at the same time. I have already uploaded it to Debian experimental. I hope @vfreex is still active on this project.

**Comment by vfreex** [comment]
Hi @dzatoah @sunweaver , I didn't have plan for that. This was initially created for my Linux based home router and I made it open source. It would be really nice if it can be uploaded for debian.

Let me know if there is anything I can help with.

**Comment by sunweaver** [comment]
> Hi @dzatoah @sunweaver , I didn't have plan for that. This was initially created for my Linux based home router and I made it open source. It would be really nice if it can be uploaded for debian.
> 
> Let me know if there is anything I can help with.

The upload has already happened and the package mdns-reflector has landed in Debian experimental. Unfortunately, we spotted this smart mDNS reflector two days late; otherwise, we would have made it for the Debian 12 release cycle. I will provide mdns-reflector for Debain 12 via bookworm-backports once the Debian 12 release has been published.

**Comment by vfreex** [comment]
Good to know that. Thank you a lot!
